[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Next.js specific configuration for Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Handle static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-XSS-Protection = "1; mode=block"

# Handle Next.js routing
[[redirects]]
  from = "/tools/:slug"
  to = "/ai/:slug"
  status = 301

[[redirects]]
  from = "/tool/:slug"
  to = "/ai/:slug"
  status = 301

[[redirects]]
  from = "/categories/:slug"
  to = "/category/:slug"
  status = 301

[[redirects]]
  from = "/admin"
  to = "/admindeepak"
  status = 301